# Generated by Django 3.1.4 on 2020-12-08 08:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('operator_id', models.CharField(max_length=10000000)),
                ('busId', models.AutoField(primary_key=True, serialize=False)),
                ('busNumber', models.CharField(max_length=200, unique=True)),
                ('busName', models.CharField(max_length=200, unique=True)),
                ('goesfrom', models.CharField(max_length=300)),
                ('goesTo', models.CharField(max_length=300)),
                ('departureTime', models.TimeField()),
                ('arrivalTime', models.TimeField()),
                ('agencyName', models.CharField(max_length=300)),
                ('stops', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=110), size=None), size=None)),
                ('seats', models.IntegerField()),
                ('bookedSeats', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None), size=None)),
                ('runsOn', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), default=['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'], size=None)),
                ('arrivesOnDay', models.IntegerField(default=1)),
                ('fare', models.FloatField()),
                ('stopsFareCutting', models.FloatField()),
                ('hasAc', models.BooleanField()),
                ('isSleeper', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('agencyName', models.CharField(max_length=128)),
                ('amountInWallet', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('passangerName', models.CharField(max_length=10028)),
                ('ticketId', models.AutoField(primary_key=True, serialize=False)),
                ('busId', models.CharField(default='-1', max_length=10028)),
                ('passengerId', models.CharField(max_length=10028)),
                ('bookedSeats', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None), size=None)),
                ('totalFare', models.FloatField(default=0.0)),
                ('bookingDate', models.DateTimeField(auto_now_add=True)),
                ('dateOfJourney', models.DateField()),
                ('isBusRunning', models.BooleanField()),
                ('operator_id', models.CharField(max_length=10000)),
                ('isCancelled', models.BooleanField(default=False)),
            ],
        ),
    ]
