# Generated by Django 3.1.4 on 2020-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='isRunning',
            field=models.BooleanField(default=True),
        ),
    ]
