# Generated by Django 3.1.4 on 2020-12-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_bus_isrunning'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='helpline',
            field=models.CharField(default='000-000-000', max_length=12),
        ),
    ]
