# Generated by Django 3.1.4 on 2020-12-09 19:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_operator_helpline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('busId', models.CharField(max_length=10000)),
                ('operator_id', models.CharField(max_length=10000)),
                ('date', models.DateField()),
                ('seatsBooked', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None), size=None)),
            ],
        ),
    ]
