# Generated by Django 3.1.4 on 2020-12-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='cancelledAmount',
            field=models.FloatField(default=0.0),
        ),
    ]
