# Generated by Django 3.1.4 on 2020-12-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_customer_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='passangerContact',
            field=models.CharField(default='000-000-000', max_length=12),
        ),
    ]
