# Generated by Django 3.1.4 on 2020-12-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20201218_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='date',
            field=models.DateField(),
        ),
    ]
